package upoanuncios;
// Generated 11-may-2020 4:09:43 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Anuncio generated by hbm2java
 */
public class Anuncio  implements java.io.Serializable {


     private Integer idAnuncio;
     private Categoria categoria;
     private Municipio municipio;
     private Tipoanuncio tipoanuncio;
     private Usuario usuario;
     private String titulo;
     private String descripcion;
     private Float precio;
     private Date fechaCreacion;

    public Anuncio() {
    }

	
    public Anuncio(Categoria categoria, Municipio municipio, Tipoanuncio tipoanuncio, Usuario usuario) {
        this.categoria = categoria;
        this.municipio = municipio;
        this.tipoanuncio = tipoanuncio;
        this.usuario = usuario;
    }
    public Anuncio(Categoria categoria, Municipio municipio, Tipoanuncio tipoanuncio, Usuario usuario, String titulo, String descripcion, Float precio, Date fechaCreacion) {
       this.categoria = categoria;
       this.municipio = municipio;
       this.tipoanuncio = tipoanuncio;
       this.usuario = usuario;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.precio = precio;
       this.fechaCreacion = fechaCreacion;
    }
   
    public Integer getIdAnuncio() {
        return this.idAnuncio;
    }
    
    public void setIdAnuncio(Integer idAnuncio) {
        this.idAnuncio = idAnuncio;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public Tipoanuncio getTipoanuncio() {
        return this.tipoanuncio;
    }
    
    public void setTipoanuncio(Tipoanuncio tipoanuncio) {
        this.tipoanuncio = tipoanuncio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


