package upoanuncios;
// Generated 22-abr-2020 18:24:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Anuncio generated by hbm2java
 */
public class Anuncio  implements java.io.Serializable {


     private Integer idAnuncio;
     private String titulo;
     private String descripcion;
     private Float precio;
     private Date fechaCreacion;
     private int fkCodPostal;
     private int fkIdTipoAnuncio;
     private int fkIdCategoria;
     private int fkIdSubCategoria;
     private int fkIdFotos;
     private int fkIdUsuario;

    public Anuncio() {
    }

	
    public Anuncio(int fkCodPostal, int fkIdTipoAnuncio, int fkIdCategoria, int fkIdSubCategoria, int fkIdFotos, int fkIdUsuario) {
        this.fkCodPostal = fkCodPostal;
        this.fkIdTipoAnuncio = fkIdTipoAnuncio;
        this.fkIdCategoria = fkIdCategoria;
        this.fkIdSubCategoria = fkIdSubCategoria;
        this.fkIdFotos = fkIdFotos;
        this.fkIdUsuario = fkIdUsuario;
    }
    public Anuncio(String titulo, String descripcion, Float precio, Date fechaCreacion, int fkCodPostal, int fkIdTipoAnuncio, int fkIdCategoria, int fkIdSubCategoria, int fkIdFotos, int fkIdUsuario) {
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.precio = precio;
       this.fechaCreacion = fechaCreacion;
       this.fkCodPostal = fkCodPostal;
       this.fkIdTipoAnuncio = fkIdTipoAnuncio;
       this.fkIdCategoria = fkIdCategoria;
       this.fkIdSubCategoria = fkIdSubCategoria;
       this.fkIdFotos = fkIdFotos;
       this.fkIdUsuario = fkIdUsuario;
    }
   
    public Integer getIdAnuncio() {
        return this.idAnuncio;
    }
    
    public void setIdAnuncio(Integer idAnuncio) {
        this.idAnuncio = idAnuncio;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public int getFkCodPostal() {
        return this.fkCodPostal;
    }
    
    public void setFkCodPostal(int fkCodPostal) {
        this.fkCodPostal = fkCodPostal;
    }
    public int getFkIdTipoAnuncio() {
        return this.fkIdTipoAnuncio;
    }
    
    public void setFkIdTipoAnuncio(int fkIdTipoAnuncio) {
        this.fkIdTipoAnuncio = fkIdTipoAnuncio;
    }
    public int getFkIdCategoria() {
        return this.fkIdCategoria;
    }
    
    public void setFkIdCategoria(int fkIdCategoria) {
        this.fkIdCategoria = fkIdCategoria;
    }
    public int getFkIdSubCategoria() {
        return this.fkIdSubCategoria;
    }
    
    public void setFkIdSubCategoria(int fkIdSubCategoria) {
        this.fkIdSubCategoria = fkIdSubCategoria;
    }
    public int getFkIdFotos() {
        return this.fkIdFotos;
    }
    
    public void setFkIdFotos(int fkIdFotos) {
        this.fkIdFotos = fkIdFotos;
    }
    public int getFkIdUsuario() {
        return this.fkIdUsuario;
    }
    
    public void setFkIdUsuario(int fkIdUsuario) {
        this.fkIdUsuario = fkIdUsuario;
    }




}


