package upoanuncios;
// Generated 22-abr-2020 4:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Anuncio generated by hbm2java
 */
public class Anuncio  implements java.io.Serializable {


     private Integer idAnuncio;
     private Categoria categoria;
     private Fotos fotos;
     private Municipio municipioByFkNombreMunicipio;
     private Municipio municipioByFkNombreMunicipio_1;
     private Subcategoria subcategoria;
     private Tipoanuncio tipoanuncio;
     private Usuario usuario;
     private String titulo;
     private String descripcion;
     private Float precio;
     private Date fechaCreacion;
     private Set mensajes = new HashSet(0);
     private Set sorteos = new HashSet(0);

    public Anuncio() {
    }

	
    public Anuncio(Categoria categoria, Fotos fotos, Municipio municipioByFkNombreMunicipio, Municipio municipioByFkNombreMunicipio_1, Subcategoria subcategoria, Tipoanuncio tipoanuncio, Usuario usuario) {
        this.categoria = categoria;
        this.fotos = fotos;
        this.municipioByFkNombreMunicipio = municipioByFkNombreMunicipio;
        this.municipioByFkNombreMunicipio_1 = municipioByFkNombreMunicipio_1;
        this.subcategoria = subcategoria;
        this.tipoanuncio = tipoanuncio;
        this.usuario = usuario;
    }
    public Anuncio(Categoria categoria, Fotos fotos, Municipio municipioByFkNombreMunicipio, Municipio municipioByFkNombreMunicipio_1, Subcategoria subcategoria, Tipoanuncio tipoanuncio, Usuario usuario, String titulo, String descripcion, Float precio, Date fechaCreacion, Set mensajes, Set sorteos) {
       this.categoria = categoria;
       this.fotos = fotos;
       this.municipioByFkNombreMunicipio = municipioByFkNombreMunicipio;
       this.municipioByFkNombreMunicipio_1 = municipioByFkNombreMunicipio_1;
       this.subcategoria = subcategoria;
       this.tipoanuncio = tipoanuncio;
       this.usuario = usuario;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.precio = precio;
       this.fechaCreacion = fechaCreacion;
       this.mensajes = mensajes;
       this.sorteos = sorteos;
    }
   
    public Integer getIdAnuncio() {
        return this.idAnuncio;
    }
    
    public void setIdAnuncio(Integer idAnuncio) {
        this.idAnuncio = idAnuncio;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Fotos getFotos() {
        return this.fotos;
    }
    
    public void setFotos(Fotos fotos) {
        this.fotos = fotos;
    }
    public Municipio getMunicipioByFkNombreMunicipio() {
        return this.municipioByFkNombreMunicipio;
    }
    
    public void setMunicipioByFkNombreMunicipio(Municipio municipioByFkNombreMunicipio) {
        this.municipioByFkNombreMunicipio = municipioByFkNombreMunicipio;
    }
    public Municipio getMunicipioByFkNombreMunicipio_1() {
        return this.municipioByFkNombreMunicipio_1;
    }
    
    public void setMunicipioByFkNombreMunicipio_1(Municipio municipioByFkNombreMunicipio_1) {
        this.municipioByFkNombreMunicipio_1 = municipioByFkNombreMunicipio_1;
    }
    public Subcategoria getSubcategoria() {
        return this.subcategoria;
    }
    
    public void setSubcategoria(Subcategoria subcategoria) {
        this.subcategoria = subcategoria;
    }
    public Tipoanuncio getTipoanuncio() {
        return this.tipoanuncio;
    }
    
    public void setTipoanuncio(Tipoanuncio tipoanuncio) {
        this.tipoanuncio = tipoanuncio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Set getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set mensajes) {
        this.mensajes = mensajes;
    }
    public Set getSorteos() {
        return this.sorteos;
    }
    
    public void setSorteos(Set sorteos) {
        this.sorteos = sorteos;
    }




}


