package upoanuncios;
// Generated 22-abr-2020 4:23:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer idCategoria;
     private String nombre;
     private Set publicidads = new HashSet(0);
     private Set anuncios = new HashSet(0);
     private Set subcategorias = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String nombre) {
        this.nombre = nombre;
    }
    public Categoria(String nombre, Set publicidads, Set anuncios, Set subcategorias) {
       this.nombre = nombre;
       this.publicidads = publicidads;
       this.anuncios = anuncios;
       this.subcategorias = subcategorias;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPublicidads() {
        return this.publicidads;
    }
    
    public void setPublicidads(Set publicidads) {
        this.publicidads = publicidads;
    }
    public Set getAnuncios() {
        return this.anuncios;
    }
    
    public void setAnuncios(Set anuncios) {
        this.anuncios = anuncios;
    }
    public Set getSubcategorias() {
        return this.subcategorias;
    }
    
    public void setSubcategorias(Set subcategorias) {
        this.subcategorias = subcategorias;
    }




}


