package upoanuncios;
// Generated 21-may-2020 18:45:06 by Hibernate Tools 4.3.1



/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private Integer idMensaje;
     private Anuncio anuncio;
     private Usuario usuarioByFkIdUsuarioDestino;
     private Usuario usuarioByFkIdUsuarioOrigen;
     private String titulo;
     private String contenido;

    public Mensaje() {
    }

    public Mensaje(Anuncio anuncio, Usuario usuarioByFkIdUsuarioDestino, Usuario usuarioByFkIdUsuarioOrigen, String titulo, String contenido) {
       this.anuncio = anuncio;
       this.usuarioByFkIdUsuarioDestino = usuarioByFkIdUsuarioDestino;
       this.usuarioByFkIdUsuarioOrigen = usuarioByFkIdUsuarioOrigen;
       this.titulo = titulo;
       this.contenido = contenido;
    }
   
    public Integer getIdMensaje() {
        return this.idMensaje;
    }
    
    public void setIdMensaje(Integer idMensaje) {
        this.idMensaje = idMensaje;
    }
    public Anuncio getAnuncio() {
        return this.anuncio;
    }
    
    public void setAnuncio(Anuncio anuncio) {
        this.anuncio = anuncio;
    }
    public Usuario getUsuarioByFkIdUsuarioDestino() {
        return this.usuarioByFkIdUsuarioDestino;
    }
    
    public void setUsuarioByFkIdUsuarioDestino(Usuario usuarioByFkIdUsuarioDestino) {
        this.usuarioByFkIdUsuarioDestino = usuarioByFkIdUsuarioDestino;
    }
    public Usuario getUsuarioByFkIdUsuarioOrigen() {
        return this.usuarioByFkIdUsuarioOrigen;
    }
    
    public void setUsuarioByFkIdUsuarioOrigen(Usuario usuarioByFkIdUsuarioOrigen) {
        this.usuarioByFkIdUsuarioOrigen = usuarioByFkIdUsuarioOrigen;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }




}


