package upoanuncios;
// Generated 22-abr-2020 18:24:58 by Hibernate Tools 4.3.1



/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private Integer idMensaje;
     private int fkIdUsuarioOrigen;
     private int fkIdUsuarioDestino;
     private int fkIdAnuncio;

    public Mensaje() {
    }

    public Mensaje(int fkIdUsuarioOrigen, int fkIdUsuarioDestino, int fkIdAnuncio) {
       this.fkIdUsuarioOrigen = fkIdUsuarioOrigen;
       this.fkIdUsuarioDestino = fkIdUsuarioDestino;
       this.fkIdAnuncio = fkIdAnuncio;
    }
   
    public Integer getIdMensaje() {
        return this.idMensaje;
    }
    
    public void setIdMensaje(Integer idMensaje) {
        this.idMensaje = idMensaje;
    }
    public int getFkIdUsuarioOrigen() {
        return this.fkIdUsuarioOrigen;
    }
    
    public void setFkIdUsuarioOrigen(int fkIdUsuarioOrigen) {
        this.fkIdUsuarioOrigen = fkIdUsuarioOrigen;
    }
    public int getFkIdUsuarioDestino() {
        return this.fkIdUsuarioDestino;
    }
    
    public void setFkIdUsuarioDestino(int fkIdUsuarioDestino) {
        this.fkIdUsuarioDestino = fkIdUsuarioDestino;
    }
    public int getFkIdAnuncio() {
        return this.fkIdAnuncio;
    }
    
    public void setFkIdAnuncio(int fkIdAnuncio) {
        this.fkIdAnuncio = fkIdAnuncio;
    }




}


