package upoanuncios;
// Generated 22-abr-2020 18:24:58 by Hibernate Tools 4.3.1



/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private String codPostal;
     private String nombreMunicipio;

    public Municipio() {
    }

    public Municipio(String codPostal, String nombreMunicipio) {
       this.codPostal = codPostal;
       this.nombreMunicipio = nombreMunicipio;
    }
   
    public String getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(String codPostal) {
        this.codPostal = codPostal;
    }
    public String getNombreMunicipio() {
        return this.nombreMunicipio;
    }
    
    public void setNombreMunicipio(String nombreMunicipio) {
        this.nombreMunicipio = nombreMunicipio;
    }




}


