package upoanuncios;
// Generated 11-may-2020 4:09:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private String codPostal;
     private String nombreMunicipio;
     private Set anuncios = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(String codPostal, String nombreMunicipio) {
        this.codPostal = codPostal;
        this.nombreMunicipio = nombreMunicipio;
    }
    public Municipio(String codPostal, String nombreMunicipio, Set anuncios) {
       this.codPostal = codPostal;
       this.nombreMunicipio = nombreMunicipio;
       this.anuncios = anuncios;
    }
   
    public String getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(String codPostal) {
        this.codPostal = codPostal;
    }
    public String getNombreMunicipio() {
        return this.nombreMunicipio;
    }
    
    public void setNombreMunicipio(String nombreMunicipio) {
        this.nombreMunicipio = nombreMunicipio;
    }
    public Set getAnuncios() {
        return this.anuncios;
    }
    
    public void setAnuncios(Set anuncios) {
        this.anuncios = anuncios;
    }




}


