package upoanuncios;
// Generated 22-abr-2020 4:23:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private String codPostal;
     private String nombreMunicipio;
     private Set anunciosForFkNombreMunicipio = new HashSet(0);
     private Set anunciosForFkNombreMunicipio_1 = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(String codPostal, String nombreMunicipio) {
        this.codPostal = codPostal;
        this.nombreMunicipio = nombreMunicipio;
    }
    public Municipio(String codPostal, String nombreMunicipio, Set anunciosForFkNombreMunicipio, Set anunciosForFkNombreMunicipio_1) {
       this.codPostal = codPostal;
       this.nombreMunicipio = nombreMunicipio;
       this.anunciosForFkNombreMunicipio = anunciosForFkNombreMunicipio;
       this.anunciosForFkNombreMunicipio_1 = anunciosForFkNombreMunicipio_1;
    }
   
    public String getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(String codPostal) {
        this.codPostal = codPostal;
    }
    public String getNombreMunicipio() {
        return this.nombreMunicipio;
    }
    
    public void setNombreMunicipio(String nombreMunicipio) {
        this.nombreMunicipio = nombreMunicipio;
    }
    public Set getAnunciosForFkNombreMunicipio() {
        return this.anunciosForFkNombreMunicipio;
    }
    
    public void setAnunciosForFkNombreMunicipio(Set anunciosForFkNombreMunicipio) {
        this.anunciosForFkNombreMunicipio = anunciosForFkNombreMunicipio;
    }
    public Set getAnunciosForFkNombreMunicipio_1() {
        return this.anunciosForFkNombreMunicipio_1;
    }
    
    public void setAnunciosForFkNombreMunicipio_1(Set anunciosForFkNombreMunicipio_1) {
        this.anunciosForFkNombreMunicipio_1 = anunciosForFkNombreMunicipio_1;
    }




}


