package upoanuncios;
// Generated 06-may-2020 5:30:17 by Hibernate Tools 4.3.1



/**
 * Publicidad generated by hbm2java
 */
public class Publicidad  implements java.io.Serializable {


     private Integer idPublicidad;
     private int titulo;
     private String descripcion;
     private String banner;
     private int fkIdCategoria;

    public Publicidad() {
    }

    public Publicidad(int titulo, String descripcion, String banner, int fkIdCategoria) {
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.banner = banner;
       this.fkIdCategoria = fkIdCategoria;
    }
   
    public Integer getIdPublicidad() {
        return this.idPublicidad;
    }
    
    public void setIdPublicidad(Integer idPublicidad) {
        this.idPublicidad = idPublicidad;
    }
    public int getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(int titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getBanner() {
        return this.banner;
    }
    
    public void setBanner(String banner) {
        this.banner = banner;
    }
    public int getFkIdCategoria() {
        return this.fkIdCategoria;
    }
    
    public void setFkIdCategoria(int fkIdCategoria) {
        this.fkIdCategoria = fkIdCategoria;
    }




}


