package upoanuncios;
// Generated 06-may-2020 5:30:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String nombreRol;
     private Set usuarios = new HashSet(0);

    public Rol() {
    }

	
    public Rol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Rol(String nombreRol, Set usuarios) {
       this.nombreRol = nombreRol;
       this.usuarios = usuarios;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


