package upoanuncios;
// Generated 11-may-2020 4:09:43 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sorteo generated by hbm2java
 */
public class Sorteo  implements java.io.Serializable {


     private Integer idSorteo;
     private int fkIdAnuncioGanador;
     private int fkIdPremio;
     private Date fechaSorteo;

    public Sorteo() {
    }

    public Sorteo(int fkIdAnuncioGanador, int fkIdPremio, Date fechaSorteo) {
       this.fkIdAnuncioGanador = fkIdAnuncioGanador;
       this.fkIdPremio = fkIdPremio;
       this.fechaSorteo = fechaSorteo;
    }
   
    public Integer getIdSorteo() {
        return this.idSorteo;
    }
    
    public void setIdSorteo(Integer idSorteo) {
        this.idSorteo = idSorteo;
    }
    public int getFkIdAnuncioGanador() {
        return this.fkIdAnuncioGanador;
    }
    
    public void setFkIdAnuncioGanador(int fkIdAnuncioGanador) {
        this.fkIdAnuncioGanador = fkIdAnuncioGanador;
    }
    public int getFkIdPremio() {
        return this.fkIdPremio;
    }
    
    public void setFkIdPremio(int fkIdPremio) {
        this.fkIdPremio = fkIdPremio;
    }
    public Date getFechaSorteo() {
        return this.fechaSorteo;
    }
    
    public void setFechaSorteo(Date fechaSorteo) {
        this.fechaSorteo = fechaSorteo;
    }




}


