package upoanuncios;
// Generated 22-abr-2020 1:58:43 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sorteo generated by hbm2java
 */
public class Sorteo  implements java.io.Serializable {


     private Integer idSorteo;
     private Anuncio anuncio;
     private Premio premio;
     private Date fechaSorteo;

    public Sorteo() {
    }

    public Sorteo(Anuncio anuncio, Premio premio, Date fechaSorteo) {
       this.anuncio = anuncio;
       this.premio = premio;
       this.fechaSorteo = fechaSorteo;
    }
   
    public Integer getIdSorteo() {
        return this.idSorteo;
    }
    
    public void setIdSorteo(Integer idSorteo) {
        this.idSorteo = idSorteo;
    }
    public Anuncio getAnuncio() {
        return this.anuncio;
    }
    
    public void setAnuncio(Anuncio anuncio) {
        this.anuncio = anuncio;
    }
    public Premio getPremio() {
        return this.premio;
    }
    
    public void setPremio(Premio premio) {
        this.premio = premio;
    }
    public Date getFechaSorteo() {
        return this.fechaSorteo;
    }
    
    public void setFechaSorteo(Date fechaSorteo) {
        this.fechaSorteo = fechaSorteo;
    }




}


