package upoanuncios;
// Generated 22-abr-2020 18:24:58 by Hibernate Tools 4.3.1



/**
 * Subcategoria generated by hbm2java
 */
public class Subcategoria  implements java.io.Serializable {


     private Integer idSubCateogoria;
     private String nombreSubCategoria;
     private String fkIdCategoria;

    public Subcategoria() {
    }

    public Subcategoria(String nombreSubCategoria, String fkIdCategoria) {
       this.nombreSubCategoria = nombreSubCategoria;
       this.fkIdCategoria = fkIdCategoria;
    }
   
    public Integer getIdSubCateogoria() {
        return this.idSubCateogoria;
    }
    
    public void setIdSubCateogoria(Integer idSubCateogoria) {
        this.idSubCateogoria = idSubCateogoria;
    }
    public String getNombreSubCategoria() {
        return this.nombreSubCategoria;
    }
    
    public void setNombreSubCategoria(String nombreSubCategoria) {
        this.nombreSubCategoria = nombreSubCategoria;
    }
    public String getFkIdCategoria() {
        return this.fkIdCategoria;
    }
    
    public void setFkIdCategoria(String fkIdCategoria) {
        this.fkIdCategoria = fkIdCategoria;
    }




}


