package upoanuncios;
// Generated 06-may-2020 5:30:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subcategoria generated by hbm2java
 */
public class Subcategoria  implements java.io.Serializable {


     private Integer idSubCateogoria;
     private String nombreSubCategoria;
     private String fkIdCategoria;
     private Set anuncios = new HashSet(0);

    public Subcategoria() {
    }

	
    public Subcategoria(String nombreSubCategoria, String fkIdCategoria) {
        this.nombreSubCategoria = nombreSubCategoria;
        this.fkIdCategoria = fkIdCategoria;
    }
    public Subcategoria(String nombreSubCategoria, String fkIdCategoria, Set anuncios) {
       this.nombreSubCategoria = nombreSubCategoria;
       this.fkIdCategoria = fkIdCategoria;
       this.anuncios = anuncios;
    }
   
    public Integer getIdSubCateogoria() {
        return this.idSubCateogoria;
    }
    
    public void setIdSubCateogoria(Integer idSubCateogoria) {
        this.idSubCateogoria = idSubCateogoria;
    }
    public String getNombreSubCategoria() {
        return this.nombreSubCategoria;
    }
    
    public void setNombreSubCategoria(String nombreSubCategoria) {
        this.nombreSubCategoria = nombreSubCategoria;
    }
    public String getFkIdCategoria() {
        return this.fkIdCategoria;
    }
    
    public void setFkIdCategoria(String fkIdCategoria) {
        this.fkIdCategoria = fkIdCategoria;
    }
    public Set getAnuncios() {
        return this.anuncios;
    }
    
    public void setAnuncios(Set anuncios) {
        this.anuncios = anuncios;
    }




}


