package upoanuncios;
// Generated 06-may-2020 5:30:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoanuncio generated by hbm2java
 */
public class Tipoanuncio  implements java.io.Serializable {


     private Integer idTipoAnuncio;
     private String nombreTipoAnuncio;
     private Set anuncios = new HashSet(0);

    public Tipoanuncio() {
    }

	
    public Tipoanuncio(String nombreTipoAnuncio) {
        this.nombreTipoAnuncio = nombreTipoAnuncio;
    }
    public Tipoanuncio(String nombreTipoAnuncio, Set anuncios) {
       this.nombreTipoAnuncio = nombreTipoAnuncio;
       this.anuncios = anuncios;
    }
   
    public Integer getIdTipoAnuncio() {
        return this.idTipoAnuncio;
    }
    
    public void setIdTipoAnuncio(Integer idTipoAnuncio) {
        this.idTipoAnuncio = idTipoAnuncio;
    }
    public String getNombreTipoAnuncio() {
        return this.nombreTipoAnuncio;
    }
    
    public void setNombreTipoAnuncio(String nombreTipoAnuncio) {
        this.nombreTipoAnuncio = nombreTipoAnuncio;
    }
    public Set getAnuncios() {
        return this.anuncios;
    }
    
    public void setAnuncios(Set anuncios) {
        this.anuncios = anuncios;
    }




}


