package upoanuncios;
// Generated 22-abr-2020 18:24:58 by Hibernate Tools 4.3.1



/**
 * Tipoanuncio generated by hbm2java
 */
public class Tipoanuncio  implements java.io.Serializable {


     private Integer idTipoAnuncio;
     private String nombreTipoAnuncio;

    public Tipoanuncio() {
    }

    public Tipoanuncio(String nombreTipoAnuncio) {
       this.nombreTipoAnuncio = nombreTipoAnuncio;
    }
   
    public Integer getIdTipoAnuncio() {
        return this.idTipoAnuncio;
    }
    
    public void setIdTipoAnuncio(Integer idTipoAnuncio) {
        this.idTipoAnuncio = idTipoAnuncio;
    }
    public String getNombreTipoAnuncio() {
        return this.nombreTipoAnuncio;
    }
    
    public void setNombreTipoAnuncio(String nombreTipoAnuncio) {
        this.nombreTipoAnuncio = nombreTipoAnuncio;
    }




}


